language: python
python:
  - "3.4"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - git submodule init
  - git submodule update
  # Get validation static configs
  - curl https://raw.githubusercontent.com/Seedstars/culture/master/code/validation/.eslintrc > .eslintrc
  - curl https://raw.githubusercontent.com/Seedstars/culture/master/code/validation/.sass-lint.yml > .sass-lint.yml
  - curl https://raw.githubusercontent.com/Seedstars/culture/master/code/validation/.prospector.yml > .prospector.yml
  - curl https://raw.githubusercontent.com/Seedstars/culture/master/code/validation/.coveragerc > .coveragerc
# command to install dependencies
install:
  - pip install -r py-requirements/dev.txt
  - nvm install 6
  - npm install
  - npm run prod
# command to run tests
script:
  - py.test -c pytest_ci.ini tests/
  - prospector  --profile-path=. --profile=.prospector.yml --path=src --ignore-patterns=static
  - bandit -r src
  - npm run coverage
  - npm run lintjs
  - npm run lintscss
