# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 01:09
from __future__ import unicode_literals

import cards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=cards.models.get_card_image_path)),
                ('waste_reduction', models.DecimalField(decimal_places=1, max_digits=6)),
                ('waste_reduction_score', models.PositiveSmallIntegerField()),
                ('difficulty_score', models.PositiveSmallIntegerField()),
                ('cost_score', models.PositiveSmallIntegerField()),
                ('sources', models.TextField(blank=True, null=True)),
                ('help_links', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('NOT_CONCERNED', 'Not concerned'), ('STARTED', 'Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
