# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20171112_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cost_score',
            field=models.SmallIntegerField(),
        ),
    ]
