# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20171121_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sources',
        ),
    ]
