# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardstat',
            name='data_sources',
        ),
        migrations.AddField(
            model_name='cardstat',
            name='data_sources',
            field=models.ManyToManyField(to='cards.DataSource'),
        ),
    ]
