# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20180101_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.CardStat'),
        ),
    ]
