# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 09:42
from __future__ import unicode_literals

from django.db import migrations


def migrate_help_links(apps, schema_editor):
    Cards = apps.get_model("cards", "Card")
    for card in Cards.objects.all():
        new_value = card.help_links
        if '\n' in new_value:
            new_value = new_value.split('\n')
        else:
            new_value = list(new_value)
        card.help_links = str(new_value)
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card_published'),
    ]

    operations = [
        migrations.RunPython(migrate_help_links),
    ]
