# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 07:16
from __future__ import unicode_literals

import base.custom_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20180405_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstat',
            name='co2_reduction',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cardstat',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cardstat',
            name='waste_reduction',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cardstat',
            name='water_use_reduction',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cardstat',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='link',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='status',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=16, null=True),
        ),
    ]
