# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 07:19
from __future__ import unicode_literals

import base.custom_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20180406_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='help_links',
            field=base.custom_models.ListField(blank=True, null=True),
        ),
    ]
