# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20180406_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(max_length=1024),
        ),
    ]

