# Generated by Django 2.0.5 on 2018-08-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20180406_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, default='other', max_length=1024, null=True),
        ),
    ]
