# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20180127_2022'),
        ('accounts', '0005_auto_20171112_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('NOT_CONCERNED', 'Not concerned'), ('STARTED', 'Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=16)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.ManyToManyField(through='accounts.UserCard', to='cards.Card'),
        ),
    ]
