# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180127_2022'),
        ('accounts', '0007_auto_20180111_0107'),
    ]

    operations = [
    ]
